variables:
- name: ApimLoggerName
  value: content-logger
- name: ApimProductId
  value: content
- name: ApimProductInstanceName
  value: $(ApimProductId)
- name: ApiName
  value: $(ApimProductId)
- name: ApiVersionNumber
  value: v1
- name: DfcContentTestsBuildId
  value: 1
- name: aspTier
  value: Standard
- name: aspInstances
  value: 3
- name: aspSize
  value: 1
- name: FunctionAppName
  value: $(ResourcePrefix)-fa
- name: FunctionalTestsSqlDatabaseConnStr
  value: 'Server=tcp:$(sharedSqlServerName).database.windows.net,1433;Initial Catalog=$(SqlDatabaseName);Persist Security Info=False;User ID=$(FunctionalTestsUser);Password=$(FunctionalTestsUserPassword);MultipleActiveResultSets=True;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;'
- name: ReleaseNeo4jUrl
  value: $(Neo4jUrlDraft)
- name: ReleaseEnvironmentName
  value: pp-draft
- name: ReleaseContentApiOptionsAction
  value: getdraftcontent
- name: ResourceGroup
  value: $(ResourcePrefix)-rg
- name: ResourcePrefix
  value: dfc-$(ReleaseEnvironmentName)-api-cont